[build]
  command = "corepack enable && pnpm install --frozen-lockfile && corepack pnpm --filter @sentinel-market/storefront build"
  publish = "apps/storefront/.next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  SITE_URL = "https://market.sentinelprime.org"
  NEXT_PUBLIC_SITE_URL = "https://market.sentinelprime.org"
  NEXT_PUBLIC_API_BASE_URL = "https://market.sentinelprime.org/.netlify/functions"
  MEDUSA_API_URL = "http://136.118.148.167:9000"
  MEDUSA_PUBLISHABLE_KEY = "pk_328841e769dad23631dd3baf9616ac30c7c9dd9fd090cf5483ca2e949d97da28"
  NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = "pk_328841e769dad23631dd3baf9616ac30c7c9dd9fd090cf5483ca2e949d97da28"
  MEDUSA_REGION_ID = "reg_01KTXBQPQZ05SY3X429VE5850G"

[context.production.environment]
  SITE_URL = "https://market.sentinelprime.org"
  NEXT_PUBLIC_SITE_URL = "https://market.sentinelprime.org"
  NEXT_PUBLIC_API_BASE_URL = "https://market.sentinelprime.org/.netlify/functions"
  MEDUSA_API_URL = "http://136.118.148.167:9000"
  MEDUSA_PUBLISHABLE_KEY = "pk_328841e769dad23631dd3baf9616ac30c7c9dd9fd090cf5483ca2e949d97da28"
  NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = "pk_328841e769dad23631dd3baf9616ac30c7c9dd9fd090cf5483ca2e949d97da28"
  MEDUSA_REGION_ID = "reg_01KTXBQPQZ05SY3X429VE5850G"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
