[build]
  command = "corepack pnpm --filter @sentinel-market/storefront build"
  publish = "apps/storefront/.next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  SITE_URL = "https://market.sentinelprime.org"
  NEXT_PUBLIC_SITE_URL = "https://market.sentinelprime.org"
  NEXT_PUBLIC_API_BASE_URL = "https://market.sentinelprime.org/.netlify/functions"
  MEDUSA_API_URL = "https://legion.sentinelprime.org"
  MEDUSA_PUBLISHABLE_KEY = "pk_4f2a7194ea759c0f8e4ac2eb8f9acc575acf9195e46d349f2a3f564eb6a59469"
  NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = "pk_4f2a7194ea759c0f8e4ac2eb8f9acc575acf9195e46d349f2a3f564eb6a59469"

[context.production.environment]
  SITE_URL = "https://market.sentinelprime.org"
  NEXT_PUBLIC_SITE_URL = "https://market.sentinelprime.org"
  NEXT_PUBLIC_API_BASE_URL = "https://market.sentinelprime.org/.netlify/functions"
  MEDUSA_API_URL = "https://legion.sentinelprime.org"
  MEDUSA_PUBLISHABLE_KEY = "pk_4f2a7194ea759c0f8e4ac2eb8f9acc575acf9195e46d349f2a3f564eb6a59469"
  NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = "pk_4f2a7194ea759c0f8e4ac2eb8f9acc575acf9195e46d349f2a3f564eb6a59469"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
